title: Om Mali
logo: /assets/img/headshot_circle.png
# description: 
# show_downloads: true
theme: jekyll-theme-minimal

<style type="text/css">

h1.title {
  # font-size: 38px;
  # color: DarkRed;
  text-align: center;
}
</style>
